# Generated by Django 4.2.16 on 2024-12-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummarizedEmail',
        ),
    ]
