# Generated by Django 4.2.16 on 2024-12-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_summarizedemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
